#!/usr/bin/env php
<?php
use Phalcon\Config\Adapter\Yaml;

define('ROOT_DIR', __DIR__ . '/');
define('APP_DIR', ROOT_DIR . 'app/');
define('DEV_ENV_DIR', ROOT_DIR . 'env/dev/');

$cmd = "rm -Rf " . escapeshellarg(DEV_ENV_DIR);
exec($cmd);

mkdir(DEV_ENV_DIR, 0777, true);
mkdir(DEV_ENV_DIR . 'cmd');
mkdir(DEV_ENV_DIR . 'public');
symlink(APP_DIR . 'assets/public', DEV_ENV_DIR . 'public/assets');

createWebEntry(DEV_ENV_DIR . 'public/index.php');
createCliEntry(DEV_ENV_DIR . 'run');

$cmdConfig = new Yaml(ROOT_DIR . 'app/config/commands.yml');
$aliases = array_keys($cmdConfig->alias->toArray());
foreach ($aliases as $alias) {
    createCliScriptAsNameEntry(DEV_ENV_DIR . 'cmd/' . $alias);
}

/**
 *
 */
function createCliScriptAsNameEntry($path) {
    $entryText = <<<'EOF'
#!/usr/bin/env php
<?php
use Perch\Application\AutoApp;

require __DIR__ . '/../../../feather-extension/require.php';

$app = new AutoApp(__DIR__ . '/../../..');
$app->run([
    'scriptNameAsCommand' => true,
]);
EOF;

    file_put_contents($path, $entryText);
    chmod($path, 0755);
}

/**
 *
 */
function createWebEntry($path) {
    $entryText = <<<'EOF'
<?php
use Perch\Application\AutoApp;

require __DIR__ . '/../../../feather-extension/require.php';
$app = new AutoApp(__DIR__ . '/../../..');
$app->run();
EOF;

    file_put_contents($path, $entryText);
}

/**
 *
 */
function createCliEntry($path) {
    $entryText = <<<'EOF'
#!/usr/bin/env php
<?php
use Perch\Application\AutoApp;

require __DIR__ . '/../../feather-extension/require.php';

$app = new AutoApp(__DIR__ . '/../..');
$app->run();
EOF;

    file_put_contents($path, $entryText);
    chmod($path, 0755);
}
