---
default:
  namespace: App\Commands
alias:
  dev: webpack
  addUser: dschissler:fancyProject:addUser
use:
  - Dschissler\FancyProject\AddUserCommand
bundle:
  - BobFrancisJr\Security\CommandBundle
...
