---
module:
  - main
route:
  singleModule: true
  default:
    module: main
service:
  preset: Perch\Di\Preset\Web
  provider:
    - WebServiceProvider
  dir:
    - common
    - web
webpack:
  constants:
    HELLO_WORLD_CONSTANT: "Hello World"
  browsers:
    - "last 5 Chrome versions"
    - "last 5 Firefox versions"
    - "Explorer >= 11"
    - "iOS >= 89"
    - "> 1% in US"
...
