---
commons:
  libframework:
  - start
browsers:
- "last 5 Chrome versions"
- "last 5 Firefox versions"
- "Explorer >= 11"
- "iOS >= 89"
- "> 2% in US"
constants:
  HELLO_WORLD_CONSTANT: "Hello World"
...